<?php
// Plugin definition
$plugin = array(
  'title' => t('Sanderson'),
  'icon' => 'sanderson.png',
  'category' => t('Panopoly'),
  'theme' => 'sanderson',
  'css' => 'sanderson.css',
  'regions' => array(
    'column1' => t('Row 1: First Column'),
    'column2' => t('Row 1: Second Column'),
    'middlecolumn1' => t('Row 2: 1 Column'),
    'secondarycolumn1' => t('Row 3: First Column'),
    'secondarycolumn2' => t('Row 3: Second Column'),
    'secondarycolumn3' => t('Row 3: Third Column'),
  ),
);
